export function mapGenre(input) {
    switch (input) {
        case 'auto-biography':
        case 'autobiographies':
        case 'autobiography':
        case 'bio':
        case 'bios':
        case 'biographical':
        case 'biographies':
        case 'biography':
        case 'biography-autobiography':
            return 'biographies/autobiographies';
        
        case 'classic':
        case 'classic-fiction':
        case 'classic-lit':
        case 'classic-literature':
        case 'clàssics':
        case 'classics':
        case 'classics-to-read':
            return 'classics';

        case 'comic':
        case 'comic-book':
            return 'comic-book/graphic novel';

        case 'cozy-mystery':
        case 'crime':
        case 'crime-and-mystery':
        case 'crime-fiction':
        case 'crime-mystery':
        case 'crime-thriller':
        case 'detective':
        case 'detective-fiction':
        case 'detectives':
        case 'mistery':
        case 'murder':
        case 'murder-mystery':
        case 'mysteries':
        case 'mystery':
        case 'mystery-crime':
        case 'mystery-detective':
        case 'whodunit':
            return 'crime/mystery';

        case 'epic-fantasy':
        case 'fairytale':
        case 'fairy-tale':
        case 'fairy-tales':
        case 'fantasia':
        case 'fantasy':
        case 'fantasy-fiction':
        case 'fantasy-scifi':
        case 'fiction-fantasy':
        case 'genre-fantasy':
        case 'high-fantasy':
        case 'magic':
        case 'modern-fantasy':
        case 'urban-fantasy':
        case 'ya-fantasy':
        case 'young-adult-fantasy':
            return 'fantasy';

        case 'historical-fiction':
            return 'historical-fiction';

        case 'historical':
        case 'history':
            return 'history';

        case 'horror':
        case 'psychological-thriller':
        case 'thriller':
        case 'thrillers':
            return 'horror/thriller';
        
        case 'comedy':
        case 'fantasy-humor':
        case 'fantasy-humour':
        case 'fiction-humor':
        case 'funny':
        case 'humor':
        case 'humorous':
        case 'humour':
            return 'humor';

        case 'autobiography-memoir':
        case 'bio-memoir':
        case 'biographies-and-memoirs':
        case 'biography-memoir':
        case 'memoir':
        case 'memoir-and-biography':
        case 'memoir-autobiography':
        case 'memoir-bio':
        case 'memoir-biography':
        case 'memoirs-biographies':
        case 'memoirs':
            return 'memoir';

        case 'personal-development':
        case 'personal-growth':
        case 'self-development':
        case 'self-help':
        case 'self-improvement':
            return 'personal-development';

        case 'philosophy':
            return 'philosophy';

        case 'reference':
            return 'reference/instructional';
                
        case 'romance':
            return 'romance';

        case 'sci-fi':
        case 'scifi':
        case 'science-fiction':
        case 'sf':
            return 'science-fiction';
        
        case 'short-stories':
        case 'short-story':
            return 'short-stories';
        
        case 'speculative':
        case 'speculative-fiction':
            return 'speculative-fiction';


        case 'روايات':
        case '1001-books-to-read-before-you-die':
        case '100-books-to-read-in-a-lifetime':
        case '1001':
        case '1001-books':
        case '1930s':
        case '1990s':
        case '2015-books':
        case '2015-challenge':
        case '2015-read':
        case '2015-reading-challenge':
        case '2015-reads':
        case '2016-books':
        case '2016-read':
        case '2016-reading-challenge':
        case '2016-reads':
        case '2016-releases':
        case '2017-books':
        case '2017-books-read':
        case '2017-read':
        case '2017-reading-challenge':
        case '2017-reading-list':
        case '2017-reads':
        case '2017-releases':
        case '2018-books':
        case '2018-challenge':
        case '2018-read':
        case '2018-reading-challenge':
        case '2018-reading-list':
        case '2018-reads':
        case '2018-want-to-read':
        case '20th-century':
        case '21st-century':
        case '4-stars':
        case '5-stars':
        case 'abandoned':
        case 'adult':
        case 'adult-fiction':
        case 'adult-non-fiction':
        case 'adult-nonfiction':
        case 'adventure':
        case 'advice':
        case 'africa':
        case 'african':
        case 'african-american':
        case 'agatha':
        case 'agatha-christie':
        case 'ai-coe':
        case 'alcoholism':
        case 'all-time-favorites':
        case 'alternate-history':
        case 'alternate-universe':
        case 'american':
        case 'american-history':
        case 'angels':
        case 'animals':
        case 'anthology':
        case 'apartheid':
        case 'apocalypse':
        case 'apocalyptic':
        case 'asia':
        case 'astronomy':
        case 'astrophysics':
        case 'audible':
        case 'audio':
        case 'audiobook':
        case 'audiobooks':
        case 'audio-book':
        case 'audio-books':
        case 'authors-of-color':
        case 'banned-books':
        case 'bbc-big-read':
        case 'best-of-2017':
        case 'biographies-memoirs':
        case 'biography-and-memoir':
        case 'black-authors':
        case 'black-history':
        case 'bookclub':
        case 'book-club':
        case 'book-club-books':
        case 'book-club-reads':
        case 'book-group':
        case 'book-to-movie':
        case 'books':
        case 'bookshelf':
        case 'books-about-books':
        case 'books-i-own':
        case 'books-read-in-2015':
        case 'books-read-in-2016':
        case 'books-read-in-2017':
        case 'borrowed':
        case 'british':
        case 'british-literature':
        case 'business':
        case 'calibre':
        case 'capitol-labor':
        case 'celebrity':
        case 'chapter-books':
        case 'childhood':
        case 'childhood-books':
        case 'childhood-faves':
        case 'childhood-favorites':
        case 'childhood-reads':
        case 'children':
        case 'children-books':
        case 'children-s':
        case 'children-s-books':
        case 'children-s-fiction':
        case 'children-s-lit':
        case 'children-s-literature':
        case 'children-ya':
        case 'children-young-adult':
        case 'childrens':
        case 'childrens-books':
        case 'childrens-fiction':
        case 'childrens-lit':
        case 'childrens-literature':
        case 'christie':
        case 'civil-rights':
        case 'coffee':
        case 'comic-fantasy':
        case 'coming-of-age':
        case 'contemporary':
        case 'contemporary-fiction':
        case 'cosmology':
        case 'couldn-t-finish':
        case 'crime-mystery-thriller':
        case 'culture':
        case 'currently-reading':
        case 'currently reading':
        case 'dark':
        case 'default':
        case 'demons':
        case 'design':
        case 'did-not-finish':
        case 'didn-t-finish':
        case 'disc-world':
        case 'discworld':
        case 'discworld-series':
        case 'discworld-witches':
        case 'diskworld':
        case 'distopia':
        case 'diversity':
        case 'dnf':
        case 'drama':
        case 'dystopia':
        case 'dystopia-utopea':
        case 'dystopian':
        case 'dystopian-fiction':
        case 'dystopian-post-apocalyptic':
        case 'dystopias':
        case 'e-book':
        case 'e-books':
        case 'ebook':
        case 'ebook-library':
        case 'ebooks':
        case 'education':
        case 'educational':
        case 'england':
        case 'english':
        case 'english-literature':
        case 'essays':
        case 'ethics-morality':
        case 'europe':
        case 'family':
        case 'fantasía':
        case 'fantasy-and-sci-fi':
        case 'fantasy-sci-fi':
        case 'faves':
        case 'Ｆａｖｏｒｉｔｅｓ':
        case 'favorite':
        case 'favorite-books':
        case 'favourite':
        case 'favorites':
        case 'favourites':
        case 'female-author':
        case 'female-authors':
        case 'female-protagonist':
        case 'feminism':
        case 'feminist':
        case 'fiction':
        case 'finished':
        case 'folklore':
        case 'for-kids':
        case 'for-school':
        case 'for-the-kids':
        case 'fun':
        case 'gaiman':
        case 'gave-up':
        case 'gave-up-on':
        case 'gender':
        case 'general':
        case 'general-fiction':
        case 'george-orwell':
        case 'germany':
        case 'gialli':
        case 'gods':
        case 'great-american-read':
        case 'have':
        case 'health':
        case 'hercule-poirot':
        case 'high-school':
        case 'his-dark-materials':
        case 'home':
        case 'homemaking':
        case 'hot-list':
        case 'housekeeping':
        case 'how-to':
        case 'humble-bumble':
        case 'i-own':
        case 'illustrated':
        case 'imaginary':
        case 'improvement':
        case 'inspiration':
        case 'inspirational':
        case 'japan':
        case 'japanese':
        case 'juvenile':
        case 'juvenile-fiction':
        case 'kid-books':
        case 'kid-lit':
        case 'kids':
        case 'kids-books':
        case 'kindle':
        case 'kindle-unlimited':
        case 'language':
        case 'learning':
        case 'library':
        case 'library-book':
        case 'library-books':
        case 'life':
        case 'lifestyle':
        case 'listened':
        case 'listened-to':
        case 'literary':
        case 'literary-fiction':
        case 'literature':
        case 'made-me-cry':
        case 'magical-realism':
        case 'math':
        case 'mathematics':
        case 'maybe':
        case 'middle-grade':
        case 'middle-school':
        case 'mine':
        case 'minimalism':
        case 'modern-classics':
        case 'movies':
        case 'mundodisco':
        case 'murakami':
        case 'must-read':
        case 'my-books':
        case 'my-childhood':
        case 'my-favorites':
        case 'my-library':
        case 'mystery-suspense':
        case 'mystery-suspense-thriller':
        case 'mystery-thriller':
        case 'mystery-thriller-suspense':
        case 'myth':
        case 'myths':
        case 'mythology':
        case 'myths-and-legends':
        case 'nature':
        case 'nebula':
        case 'nebula-award':
        case 'nebula-award-winners':
        case 'nebula-winners':
        case 'need-to-buy':
        case 'neil-gaiman':
        case 'never-finished':
        case 'nf':
        case 'non-fiction':
        case 'non-fiction-science':
        case 'non-fiction-to-read':
        case 'nonfiction':
        case 'nonfiction-science':
        case 'nonfiction-to-read':
        case 'non-fic':
        case 'nonfic':
        case 'norse':
        case 'norse-mythology':
        case 'nostalgia':
        case 'novel':
        case 'novels':
        case 'occult':
        case 'octavia-butler':
        case 'on-hold':
        case 'on-kindle':
        case 'on-my-shelf':
        case 'organization':
        case 'organizing':
        case 'other':
        case 'overdrive':
        case 'own-it':
        case 'owned':
        case 'owned-books':
        case 'owned-to-read':
        case 'paper':
        case 'paranormal':
        case 'paula-hawkins':
        case 'philip-pullman':
        case 'physics':
        case 'place':
        case 'po':
        case 'poc':
        case 'poc-author':
        case 'poirot':
        case 'political':
        case 'politics':
        case 'popular-science':
        case 'post-apocalyptic':
        case 'pratchett':
        case 'pratchett-terry':
        case 'productivity':
        case 'psychological':
        case 'psychology':
        case 'race':
        case 'racism':
        case 're-read':
        case 're-reads':
        case 'read-again':
        case 'read-aloud':
        case 'read-alouds':
        case 'read-as-a-kid':
        case 'read-for-school':
        case 'read-harder-2017':
        case 'read-harder-2018':
        case 'read-in-2012':
        case 'read-in-2013':
        case 'read-in-2014':
        case 'read-in-2015':
        case 'read-in-2016':
        case 'read-in-2017':
        case 'read-in-2018':
        case 'ℜead-in-2018':
        case 'read-more-than-once':
        case 'read-2015':
        case 'read-2016':
        case 'read-2017':
        case 'read-2018':
        case 'read-in-english':
        case 'realistic-fiction':
        case 'recommend':
        case 'recommended':
        case 'religion':
        case 'reread':
        case 'retelling':
        case 'retellings':
        case 'reviewed':
        case 'rory-gilmore-reading-challenge':
        case 'satire':
        case 'scandinavia':
        case 'school':
        case 'school-books':
        case 'science-fiction-and-fantasy':
        case 'science-fiction-fantasy':
        case 'science-nature':
        case 'science-non-fiction':
        case 'science-technology':
        case 'scifi-fantasy':
        case 'sci-fi-and-fantasy':
        case 'sci-fi-fantasy':
        case 'science':
        case 'science-and-technology':
        case 'science-math':
        case 'science-tech':
        case 'sciences':
        case 'self':
        case 'series':
        case 'series-discworld':
        case 'séries':
        case 'sf-fantasy':
        case 'sf-f':
        case 'sff':
        case 'shelfari-favorites':
        case 'silicon-valley':
        case 'social-issues':
        case 'social-justice':
        case 'south-africa':
        case 'space':
        case 'stand-alone':
        case 'steampunk':
        case 'stem':
        case 'stopped-reading':
        case 'stories':
        case 'supernatural':
        case 'suspense':
        case 'suspense-thriller':
        case 'tbr':
        case 'technology':
        case 'technology-management':
        case 'teen':
        case 'terry-pratchet':
        case 'terry-pratchett':
        case 'thinking-about-reading':
        case 'three-stars':
        case 'thriller-mystery':
        case 'thriller-suspense':
        case 'to-buy':
        case 'to-re-read':
        case 'to-read-science':
        case 'to-reread':
        case 'to-read':
        case 'to-read-again':
        case 'to-read-nonfiction':
        case 'to-read-non-fiction':
        case 'to-read-own':
        case 'translated':
        case 'trilogy':
        case 'unfinished':
        case 'universe':
        case 'unreliable-narrator':
        case 'via-g':
        case 'vikings':
        case 'want-to-buy':
        case 'wish-list':
        case 'witchcraft':
        case 'witches':
        case 'women':
        case 'women-authors':
        case 'women-s-history':
        case 'world-war-ii':
        case 'ya':
        case 'ya-books':
        case 'ya-fiction':
        case 'ya-lit':
        case 'young':
        case 'young-adult':
        case 'young-adult-fiction':
        case 'young-readers':
        case 'youngadult':
        case 'youth':
            return 'NOT A GENRE';
 
        default:
            return 'UNIDENTIFIED: ' + input; 
    }
};
